spring:
  application:
    name: corsError
  profiles:
    active: ${ACTIVE_PROFILE:default}

custom:
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://www.perplexity.ai
    allowed-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
